# Generated by Django 4.2.9 on 2024-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_address_user_avatar_user_first_name_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="document",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
