# Generated by Django 4.2.9 on 2024-01-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="document",
        ),
    ]
