# Generated by Django 4.2.9 on 2024-03-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar",
            new_name="avatar_image",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="birth_of_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("free", "Free"), ("premium", "Premium")], default="free", max_length=255),
        ),
    ]
