# Generated by Django 4.2.9 on 2024-03-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_avatar_user_avatar_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="birth_of_date",
            new_name="birthday",
        ),
    ]
