# Generated by Django 4.2.9 on 2024-01-29 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waitlist", "0002_waitdocument"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="waitdocument",
            unique_together={("user_id", "tendr_id")},
        ),
        migrations.RemoveField(
            model_name="waitdocument",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="waitdocument",
            name="updated_at",
        ),
    ]
