# Generated by Django 4.2.9 on 2024-01-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CftFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("addendum_id", models.CharField(blank=True, max_length=2048, null=True)),
                ("title", models.CharField(blank=True, max_length=2048, null=True)),
                ("file", models.CharField(blank=True, max_length=2048, null=True, unique=True)),
                ("description", models.CharField(blank=True, max_length=2048, null=True)),
                ("lang", models.CharField(blank=True, max_length=2048, null=True)),
                ("doument_version", models.CharField(blank=True, max_length=2048, null=True)),
                ("action", models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=2048, null=True)),
                ("resource_id", models.CharField(max_length=2048, unique=True)),
                ("ca", models.CharField(blank=True, max_length=2048, null=True)),
                ("info", models.TextField(blank=True, null=True)),
                ("date_published", models.DateTimeField(blank=True, null=True)),
                ("tenders_submission_deadline", models.CharField(blank=True, max_length=2048, null=True)),
                ("procedure", models.CharField(blank=True, max_length=2048, null=True)),
                ("status", models.CharField(blank=True, max_length=2048, null=True)),
                ("notice_pdf", models.CharField(blank=True, max_length=2048, null=True)),
                ("award_date", models.CharField(blank=True, max_length=2048, null=True)),
                ("estimated_value", models.FloatField(blank=True, default=None, null=True)),
                ("cycle", models.CharField(blank=True, max_length=2048, null=True)),
                ("tender_detail", models.JSONField(blank=True, default=dict, null=True)),
                ("cpv_code", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cft_files", models.ManyToManyField(to="scrape.cftfile")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organisation_name", models.CharField(blank=True, max_length=2048, null=True)),
                ("ca_abbreviation", models.CharField(blank=True, max_length=2048, null=True)),
                ("ca_type", models.CharField(blank=True, max_length=2048, null=True)),
                ("annex", models.CharField(blank=True, max_length=2048, null=True)),
                ("address", models.CharField(blank=True, max_length=2048, null=True)),
                ("eircode_or_postal_code", models.CharField(blank=True, max_length=2048, null=True)),
                ("city", models.CharField(blank=True, max_length=2048, null=True)),
                ("county", models.CharField(blank=True, max_length=2048, null=True)),
                ("email", models.CharField(blank=True, max_length=2048, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=2048, null=True)),
                ("fax", models.CharField(blank=True, max_length=2048, null=True)),
                ("website", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "tendr_id",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="scrape.tender",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
